### ISSUE TITLE
Allow complex selectors inside :not(), or a way to select sibling nodes between two nodes

### ISSUE THREAD

**Issue by dbuijs** [hadley/rvest#105]
Is there a way to select all sibling nodes between 2 nodes? I am able to use complex CSS selectors inside the :not() pseudoselector in SelectorGadget but not in `rvest`, and it looks like the reason for this is that SelectorGadget does more than advertised, not that there's anything wrong with `rvest`.

I'm trying to use `rvest` to extract text from valid, but poorly structured html. The documents have headings, but the text under them is dumped as sibling nodes of assorted types, without a parent node to contain the heading and the text. Here's an example:

    <h2 id="heading1'> This is Heading 1 </h2>
    <p> Some text in section1 </p>
    <p> Some more text in section 1 </p>
    <ul>
         <li> Some random list in Section 1 </li>
    </ul>
    <h2 id="heading2"> This is Heading 2 </h2>
    <p> Some text in section 2 </p>
    <p> Some more text in section 2 </p>

What I'm after is all the sibling nodes between the Headings. In SelectorGadget, I can come close to this with the following CSS (it still selects the second h2, but I can deal with that later):

    h2:contains("Heading 1") ~ *:not(h2:contains("Heading 2") ~ *)

It turns out that this won't run in `rvest` because the actual CSS specification is to only allow simple selectors inside the `:not()` pseudoselector. Is it possible to get `rvest` to work the same way as SelectorGadget? Alternately, is there another way in `rvest` or friends to select all sibling nodes between two nodes? I totally understand that there will be no :bewteen() pseudoselector in CSS and that there are good reason for this. People who use CSS in `rvest` aren't looking to style webpages though, they want to extract data/text from XML/HTML. 

Any thoughts?

**Comment by hadley** [comment]
Have you tried using the xpath output from selector gadget?

**Comment by dbuijs** [comment]
That's a very good question. I hadn't tried that. Unfortunately, the following CSS in SelectorGadget:

    h2:contains("Heading 1") ~ *:not(h2:contains("Heading 2") ~ *)

Gets turned into the following xpath:

    //h2//1')//~//*//2')//~//*)

Which doesn't even look like valid xpath and `html_nodes` throws an error evaluating xpath. on the first single quote. As I said before, I don't think there is anything wrong with `rvest`, I think SelectorGadget is doing something undocumented that could be very useful. 

Please feel free to mark as a feature request and/or close as out of scope.

**Comment by hadley** [comment]
You could file it as a bug in the selectr package, which is what rvest uses to convert css to xpath. Otherwise, it's probably possible to do by hand, if you learn a bit of xpath (which is moderately horrible). A final alternative is to try doing it in R - you might be able to use `html_tag()` to find the right places to index into `html_text()`.

**Comment by dbuijs** [comment]
For the sake of anyone else who is trying to use `rvest` to extract all sibling nodes between two nodes of the same type (including myself when I forget about how I did it the first time):

Firstly, caveat emptor on using SelectorGadget to translate CSS you write yourself into XPath. SelectorGadget can only generate reliable XPath for CSS selectors it generates itself. 

The XPath problem was actually easier than I thought, because the two bounding nodes are of the same type. The following XPath does the trick:

    //*[preceding-sibling::h2[1][contains(text(), "Heading 1")]]

This selects second bounding node too (i.e. "Heading 2"), but you can drop the last node easily with another `html_nodes` step.
