### ISSUE TITLE
Documentation should be updated

### ISSUE THREAD

**Issue by jeffisabelle** [hadley/rvest#106]
Hey, I just started using rvest by installing it from CRAN. 
The readme file seems kind of outdated. It states that reading html should be like as this.

`read_html(params)`

But it doesn't appear on the environment after loading rvest package. There is a `html(params)` function though.

I forked the repo to contribute and wanted to change the the documentation. However after looking 
the source code a little bit, I found the following comment in `R/parse.R` and couldn't decide if the
function should be `read_html` or docs are just outdated.

```#' html is deprecated: please use \code{read_html}() instead.```

But the function signature is still `html()` and calling `read_html()` throws an error. 

Thanks!

**Comment by hadley** [comment]
Fixed in dev
