### ISSUE TITLE
rvest::read_html gives namespace error

### ISSUE THREAD

**Issue by markdanese** [hadley/rvest#109]
It looks like read_html is straight from xml2 and gives this error when I try to put this into a script explicitly.  There is no issue when I use it after calling `library(rvest)` first.  Also, if I replace "rvest" with "xml2" in the code below it works fine. Not really sure if this needs to be "fixed" but wanted to at least mention it.  [By the way, thanks for this package.  I have done some really useful things with it.]

`rvest::read_html("https://www.facs.org/search/trauma-centers?state=AL&n=250")`

`Error: 'read_html' is not an exported object from 'namespace:rvest'`

**Comment by juancentro** [comment]
That's right, I get a message stating

```
'rvest::html' is deprecated.
Use 'read_html' instead.
See help("Deprecated") 
```

but I can't use `rvest::read_html`.

Maybe it isn't reexported from `xml2`?

**Comment by hadley** [comment]
Yes, `read_html` is in xml2.
