### ISSUE TITLE
html_text should complete with NAs when there is no data

### ISSUE THREAD

**Issue by OmarGonD** [hadley/rvest#110]
Hi Hadley, thanks for your work.

This is a big problem when doing web scrapping. Somethings have always a value (like: actual price), but no other values associated (like: old price). Some elements have both, but when using `html_text()`, a string with actual.price has, for example, 20 elements, while old.price has 16 elements. 

This makes it difficult to make comparisions, if `html_text()` would consider NA instead of nothing we could replace it with "0" or other values. 

Thanks.

There is a question about this issue on stackoverflow:

http://stackoverflow.com/questions/30721519/rvest-package-is-it-possible-for-html-text-to-store-an-na-value-if-it-does-n

**Comment by hadley** [comment]
Please provide a minimal reprex.

**Comment by OmarGonD** [comment]
Hadley, this is my code. As you can see in the image attached, the vectors: 1 ) saga.todo.led.precio.actual1 and 2) saga.todo.led.precio.antes1 dont have the same length. 

Same for the "precio.actual2", "precio.antes2".  It would very helpfull, when no value is found, rvest puts NA. 

This could be also a problem of the page itself, since in some sections I get 2 vectors of the same length for "precio.actual1", "precio.antes1" and "precio.actual2", "precio.antes2".  For example in this page: "http://www.falabella.com.pe/falabella-pe/category/cat1450502/Smart-TV?navAction=push". It would be nice to have a standar. Thanks.


![rvest-issue](https://cloud.githubusercontent.com/assets/7775734/10223962/57f32790-6821-11e5-8c24-3926a9c8992e.png)





library(RSelenium)
library(rvest)
library(reshape2)
library(stringr)
library(dplyr)
library(ggplot2)




##############################################################################
############ TODO LED ########################################################
##############################################################################
#start RSelenium
checkForServer()
startServer()
remDr <- remoteDriver()
remDr$open()


remDr$navigate("http://www.falabella.com.pe/falabella-pe/category/cat1450492/Todo-TV-LED?No=0&Nrpp=16")

Sys.sleep(3)

page_source<-remDr$getPageSource()

#Marca

saga.todo.led.marca1 <- read_html(iconv(page_source[[1]], to="UTF-8"), encoding = "utf8") %>%
        #xml_structure() %>%
        html_nodes(".marca") %>%
        html_text_na()


saga.todo.led.marca1 <-   gsub("\n", "", saga.todo.led.marca1)
saga.todo.led.marca1 <-   gsub("\t", "", saga.todo.led.marca1)


#Producto Página 1


saga.todo.led.producto1 <- read_html(iconv(page_source[[1]], to="UTF-8"), encoding = "utf8") %>%
        #xml_structure() %>%
        html_nodes(".detalle") %>%
        html_text()


saga.todo.led.producto1 <-   gsub("\n", "", saga.todo.led.producto1)
saga.todo.led.producto1 <-   gsub("\t", "", saga.todo.led.producto1)


#Precio Actual Página 1


saga.todo.led.precio.actual1 <- read_html(iconv(page_source[[1]], to="UTF-8"), encoding = "utf8") %>%
        html_nodes(".precio1") %>%
        html_text()


saga.todo.led.precio.actual1 <-   gsub("\n", "", saga.todo.led.precio.actual1)
saga.todo.led.precio.actual1 <-   gsub("\t", "", saga.todo.led.precio.actual1)
saga.todo.led.precio.actual1 <-   gsub("\\S\\/\\.", "", saga.todo.led.precio.actual1)
saga.todo.led.precio.actual1 <-   gsub(",", "", saga.todo.led.precio.actual1)
saga.todo.led.precio.actual1 <-   gsub(".* ", "", saga.todo.led.precio.actual1)



#Precio Antiguo Página 1


saga.todo.led.precio.antes1 <- read_html(iconv(page_source[[1]], to="UTF-8"), encoding = "utf8") %>%
        html_nodes(".precio2") %>%
        html_text()


saga.todo.led.precio.antes1 <-   gsub("\n", "", saga.todo.led.precio.antes1)
saga.todo.led.precio.antes1 <-   gsub("\t", "", saga.todo.led.precio.antes1)
saga.todo.led.precio.antes1 <-   gsub("\\S\\/\\.", "", saga.todo.led.precio.antes1)
saga.todo.led.precio.antes1 <-   gsub(",", "", saga.todo.led.precio.antes1)
saga.todo.led.precio.antes1 <-   gsub(".* ", "", saga.todo.led.precio.antes1)



#Opción retiro en tienda

saga.todo.led.retiro.tienda1 <- read_html(iconv(page_source[[1]], to="UTF-8"), encoding = "utf8") %>%
        html_nodes(".ico_cuatro") %>%
        html_text()


saga.todo.led.retiro.tienda1 <-   gsub("\n", "", saga.todo.led.retiro.tienda1)
saga.todo.led.retiro.tienda1 <-   gsub("\t", "", saga.todo.led.retiro.tienda1)

#Del total de productos
#solo 8 se pueden comprar y retirar en tienda

length(saga.todo.led.retiro.tienda1)

########################################


##############@################
# Todo LED - Page 2
# Extraer marca, producto, y precio
#################################


Sys.sleep(3)

remDr$navigate("http://www.falabella.com.pe/falabella-pe/category/cat1450492/Todo-TV-LED?No=16&Nrpp=16")

Sys.sleep(5)


page_source<-remDr$getPageSource()


######### Page 2  - Marca

saga.todo.led.marca2 <- read_html(iconv(page_source[[1]], to="UTF-8"), encoding = "utf8") %>%
        html_nodes(".marca") %>%
        html_text()


saga.todo.led.marca2 <-   gsub("\n", "", saga.todo.led.marca2)
saga.todo.led.marca2 <-   gsub("\t", "", saga.todo.led.marca2)


#Producto Página 2


saga.todo.led.producto2 <- read_html(iconv(page_source[[1]], to="UTF-8"), encoding = "utf8") %>%
        html_nodes(".detalle") %>%
        html_text()


saga.todo.led.producto2 <-   gsub("\n", "", saga.todo.led.producto2)
saga.todo.led.producto2 <-   gsub("\t", "", saga.todo.led.producto2)


#Precio Actual Página 2


saga.todo.led.precio.actual2 <- read_html(iconv(page_source[[1]], to="UTF-8"), encoding = "utf8") %>%
        html_nodes(".precio1") %>%
        html_text()


saga.todo.led.precio.actual2 <-   gsub("\n", "", saga.todo.led.precio.actual2)
saga.todo.led.precio.actual2 <-   gsub("\t", "", saga.todo.led.precio.actual2)
saga.todo.led.precio.actual2 <-   gsub("\\S\\/\\.", "", saga.todo.led.precio.actual2)
saga.todo.led.precio.actual2 <-   gsub(",", "", saga.todo.led.precio.actual2)
saga.todo.led.precio.actual2 <-   gsub(".* ", "", saga.todo.led.precio.actual2)


#Precio Antiguo Página 2


saga.todo.led.precio.antes2 <- read_html(iconv(page_source[[1]], to="UTF-8"), encoding = "utf8") %>%
        html_nodes(".precio2") %>%
        html_text()


saga.todo.led.precio.antes2 <-   gsub("\n", "", saga.todo.led.precio.antes2)
saga.todo.led.precio.antes2 <-   gsub("\t", "", saga.todo.led.precio.antes2)
saga.todo.led.precio.antes2 <-   gsub("\\S\\/\\.", "", saga.todo.led.precio.antes2)
saga.todo.led.precio.antes2 <-   gsub(",", "", saga.todo.led.precio.antes2)
saga.todo.led.precio.antes2 <-   gsub(".* ", "", saga.todo.led.precio.antes2)

#Opción retiro en tienda 2

saga.todo.led.retiro.tienda2 <- read_html(iconv(page_source[[1]], to="UTF-8"), encoding = "utf8") %>%
        html_nodes(".ico_cuatro") %>%
        html_text_na()


saga.todo.led.retiro.tienda2 <-   gsub("\n", "", saga.todo.led.retiro.tienda1)
saga.todo.led.retiro.tienda2 <-   gsub("\t", "", saga.todo.led.retiro.tienda1)


#error not same length

ff <- data.frame(saga.todo.led.precio.actual1,
                 saga.todo.led.precio.antes1)

**Comment by hadley** [comment]
Please work on a minimal example, that is less than 10 lines of code.

**Comment by OmarGonD** [comment]
I'm sorry Hadley. Re checking my code there was a mistake. Now it works perfect. 
However there is the issue over stackoverflow, I don't know if the best is to delete this issue. 
Sorry again.
