### ISSUE TITLE
html_text should complete with NAs when  node does not exist

### ISSUE THREAD

**Issue by OmarGonD** [hadley/rvest#112]
Hi Hadley, this is the core of the problem: 

Products are surrounded by div with class: "product_price". Inside we find the "old price" (class = "normal_encontrado" and/or "new price" (class = "price").

Is there a way to tell rvest to: 

-If no 'class' fund put NA, otherwise extract data? Making it so, we'll end with 2 vectors of the same length, making it possible to cbind them into a data frame. Thanks.

As you see, the first div has the 2 classes, while second div only the class "price". 

# HTML 
```html
<html>
<head></head>
<body>

<div class="product_price" id="product_price_186251">
			<!-- BEGIN PriceDisplay.jsp --><!-- BEGIN RipleyCatalogEntryPriceDisplay.jspf-->
				<p class="normal_encontrado">
					S/. 2,799.00
				</p>
			 
					<div id="WC_CatalogEntryDBThumbnailDisplayJSPF_10461_div_10" class="price">
				 		S/. 2,299.00
					</div>
				<!-- END RipleyCatalogEntryPriceDisplay.jspf--><!-- END PriceDisplay.jsp -->

</div>


<div class="product_price" id="product_price_232046">
			<!-- BEGIN PriceDisplay.jsp --><!-- BEGIN RipleyCatalogEntryPriceDisplay.jspf-->
					<div id="WC_CatalogEntryDBThumbnailDisplayJSPF_10461_div_10" class="price">
						S/. 4,999.00
					</div>
				<!-- END RipleyCatalogEntryPriceDisplay.jspf--><!-- END PriceDisplay.jsp -->

</div>
</body>
</html>
```

# R Code
library(rvest)

page_source <- read_html("r2.html")

r.precio.antes <- page_source %>%
        #xml_structure() %>%
        html_nodes(".normal_encontrado") %>%
        html_text()

r.precio.actual <- page_source %>%
        #xml_structure() %>%
        html_nodes(".price") %>%
        html_text()

**Comment by hadley** [comment]
Again, can you please make a simple reproducible example. Reduce the problem down to a small xml example that you can include inline, and a few lines of code.

**Comment by OmarGonD** [comment]
Hi Hadley, I've posted a minimal code example. 

Also, I found some answers in Stackoverflow, in case you may want to check them:

http://stackoverflow.com/questions/30721519/rvest-package-is-it-possible-for-html-text-to-store-an-na-value-if-it-does-n

http://stackoverflow.com/questions/29877451/rvest-missing-nodes-na

**Comment by hadley** [comment]
I'm pretty sure this is just a duplicate of #82

**Comment by OmarGonD** [comment]
I'll check that out. Thank you.
