### ISSUE TITLE
Ignore no robots/robot detections?

### ISSUE THREAD

**Issue by Deleetdk** [hadley/rvest#115]
I am trying to scrape [this page](http://www.thefruitpages.com/contents.shtml) for nutritional content of fruits. However, using `read_html(http://www.thefruitpages.com/contents.shtml)` gives the result:

    {xml_document}
    <html>
    [1] <head>\n  <title>Request Rejected</title>\n</head>
    [2] <body>The requested URL was rejected. If you think this is an error, please contact the webmaster. <br/><b ...

My guess is that the website refuses to let the scraper download the material. Presumably, it is detecting the scraper through the HTML request.

Is there some way to get around this limitation?

**Comment by hadley** [comment]
They often look at the user agent.

**Comment by Deleetdk** [comment]
As hadley said, the solution was to change the user agent in the request. The following works:

    ua = "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:33.0) Gecko/20100101 Firefox/33.0"
    index = read_html(GET("http://www.thefruitpages.com/contents.shtml",
                      user_agent(ua)))

after which one can just use the normal rvest function on index.
