### ISSUE TITLE
trim argument in html_table has no effect

### ISSUE THREAD

**Issue by joranE** [hadley/rvest#120]
Another skiing website example:

    skiing_url <- "http://data.fis-ski.com/dynamic/results.html?sector=CC&raceid=26692"
    tbl <- read_html(skiing_url) %>% html_table(fill = TRUE,trim = TRUE) %>% magrittr::extract2(2)
    str(tbl)

I get leading or trailing whitespace on all the character columns. I apologize for reporting this here, as I suspect that the problem is actually occurring in xml2, but faster for me to share an example without trying to only use xml2.

I ran this using rvest 0.3.1, xml2 0.1.2 and R 3.2.2 on OSX El Capitan.

**Comment by hadley** [comment]
This doesn't seem to be an xml2 bug:

```R
read_xml("<a>   asdfsd</a>") %>% xml_text(trim = TRUE)
# [1] "asdfsd"
```

**Comment by hadley** [comment]
Ah, the problem is that those aren't regular spaces - they're non-breaking spaces which trim doesn't handle. Using utf-8 compliant whitespace handling would add a lot of extra dependencies so I think you'll have to handle this yourself.
