### ISSUE TITLE
Error on submit_form when no submit button exists - option list action

### ISSUE THREAD

**Issue by mobcdi** [hadley/rvest#121]
How can I use submit_form on forms where there is no submit button, that is to say forms where the selecting of a value from an option list tiggers updating the content of the webpage based on the option selected
```
searchQuery <-"Accounting"
UCCModules <-"http://www.ucc.ie/modules/"
UCCForm <- html_form(read_html("http://www.ucc.ie/modules/")) [[1]]
#Set Values
set_values(UCCForm, menu1 = searchQuery)
#Submit the form
UCCReturn <- submit_form(form = UCCForm)
```
returns 
Error in names(submits)[[1]] : subscript out of bounds

**Comment by hadley** [comment]
That's done with javascript, so you can't use rvest. Try RSelenium or similar.
