### ISSUE TITLE
Beginner at rvest

### ISSUE THREAD

**Issue by mzorgdrager** [hadley/rvest#131]
Hello,

I am new to rvest and I am trying to parse html info into a table.
I found the required data on the website ".list td" using SelectorGadget.
I use the following code:

library(rvest)
arjanbigyear <- read_html("http://world.observation.org/arjan.php") %>%
html_nodes(".list td") %>%
html_table() 

However I get the error Error: html_name(x) == "table" is not TRUE
When I look at my Environment I see that "arjanbigyear" is a large xml_nodeset. How come this is not a html nodeset? And how do I turn the ".list td" into a datatable?

**Comment by hadley** [comment]
Because `xml_nodeset`s are `html_nodeset`s.  

You need to select the table, not the individual cells (probably `.list table`).
