### ISSUE TITLE
Issue opening connection to website 

### ISSUE THREAD

**Issue by pssguy** [hadley/rvest#136]
Not sure this an rvest issue but there is a url I can open without problem in a Chrome browser but  is unavailable using rvest

    library(rvest)

    u <- "https://github.com/issues?q=is%3Aissue+author%3Atimelyportfolio+is%3Aopen"

    dom <-read_html(u)
    Error in open.connection(x, "rb") : HTTP error 404

    library(httr)

    http_status(u)
    Error in UseMethod("status_code") : 
      no applicable method for 'status_code' applied to an object of class "character"

TIA

**Comment by hadley** [comment]
That page only seems to be accessible if you're logged into github

**Comment by askhari139** [comment]
Facing the same issue with the following link.
https://www.doi2bib.org/bib/10.1021/acsomega.9b00326
