### ISSUE TITLE
demo() does not work for 'united' or 'zillow'

### ISSUE THREAD

**Issue by sco-lo-digital** [hadley/rvest#138]
Hi,

calling demo(united, package="rvest") leads to error "Error: No links have text 'Account'"

calling demo(zillow, package="rvest") leads to "Error in eval(expr, envir, enclos) : No matches"

demo for tripadvisor works :+1: 

I'm guessing webpages changed. Perhaps you want to update?

Thanks
Scott

**Comment by jlewis91** [comment]
For Zillow, see PR #139.

**Comment by sco-lo-digital** [comment]
Thanks guys!
