### ISSUE TITLE
html_node should warn if no match

### ISSUE THREAD

**Issue by MichaelChirico** [hadley/rvest#142]
Trying to scrape the first column of this table:

http://www.hockeydb.com/ihdb/stats/leagues/seasons/nhl19271927.html

```
u <- "http://www.hockeydb.com/ihdb/stats/leagues/seasons/nhl19271927.html"

read_html(u) %>%
  html_node("tbody") %>% html_nodes("tr") %>% html_node("td")
```

The above could would get me what I want _except_ the middle rows of the table are all filled with `<th>` tags, so that I get:

> Error: No matches

In addition to the warnings about finding other cells, which are fine.

Seems like a warning here would be fine, no?

**Comment by hadley** [comment]
It now returns "missing" nodes
