### ISSUE TITLE
Documentation: rvest needs to explain which version of xpath users can expect

### ISSUE THREAD

**Issue by MichaelChirico** [hadley/rvest#143]
It's not clear from `?html_node` what version of `XPath` is supported by queries in `rvest`.

I bring this up because of the apparent importance of `XPath` 1.0 vs. 2.0 in terms of recognizing regular expressions, see [here](http://stackoverflow.com/questions/21405267/xpath-using-regex-in-contains-function).

Given that a `matches` query returned an error, it seems we should add that the supported version is 1.0.

**Comment by hadley** [comment]
@jimhester do you know what version of xpath libxml2 supports?

**Comment by jimhester** [comment]
From http://xmlsoft.org/index.html it looks like 1.0.
