### ISSUE TITLE
NA when node is missing

### ISSUE THREAD

**Issue by myliserta** [hadley/rvest#144]
Hello everyone,
I am having this case scenario:
Trying to harvest some data for educational purposes from Tripadvisor. When I scrape the reviews, sometimes, there are pages where not all the nodes are there. For example, the location of the member, in some posts is missing. Is there a way rvest would fill in a NA value instead of throwing an error?
Thank you,
D

**Comment by hadley** [comment]
It now does :)

**Comment by myliserta** [comment]
Wow, thank you :)
