### ISSUE TITLE
Extract more than text in cells for html_table?

### ISSUE THREAD

**Issue by noamross** [hadley/rvest#145]
Sometimes table cells contain information beyond that extracted via `html_text()`, which is what is run on each cell in `html_table()`.  For instance, some table cells might contain links. Would you accept a PR that allows extraction of the full HTML contents of cells?

This would take the form of an additional argument to `html_table()` (`html_contents`), that would be FALSE by default.

@daattali

**Comment by noamross** [comment]
Closing this as I'm concluding it's better to work with the pandoc JSON than the HTML for import.

**Comment by BenoitLondon** [comment]
I m interested in this feature as well. Can you elaborate why you closed this?
