### ISSUE TITLE
export `read_html`

### ISSUE THREAD

**Issue by curtisalexander** [hadley/rvest#163]
Is there any reason `read_html` is not exported?  Taking the example from the `README`, I can run

```
library(rvest)
lego_movie <- read_html("http://www.imdb.com/title/tt1490017/")

rating <- lego_movie %>% 
  html_nodes("strong span") %>%
  html_text() %>%
  as.numeric()
rating
```

without any issue.  But if instead I run the following

```
lego_movie <- rvest::read_html("http://www.imdb.com/title/tt1490017/")
```

I get the error 

```
Error: 'read_html' is not an exported object from 'namespace:rvest'
```

Session info below as well as the package version of `rvest` (I'm using the development version from Github).

```
> sessionInfo()
R version 3.3.1 (2016-06-21)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X 10.11.3 (El Capitan)

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] rsconnect_0.4.3 tools_3.3.1   
```

Package version.

```
library("dplyr")
installed.packages() %>%
  as.data.frame(stringsAsFactors=FALSE) %>%
  dplyr::select(Package, Version, Depends, Imports, LibPath, Built) %>%
  dplyr::distinct(Package, Version, Depends, Imports, LibPath, Built) %>%
  dplyr::as_data_frame() %>%
  dplyr::filter(Package %in% c("rvest")) %>%
  knitr::kable(format = "html")
```

<table>
 <thead>
  <tr>
   <th style="text-align:left;"> Package </th>
   <th style="text-align:left;"> Version </th>
   <th style="text-align:left;"> Depends </th>
   <th style="text-align:left;"> Imports </th>
   <th style="text-align:left;"> LibPath </th>
   <th style="text-align:left;"> Built </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> rvest </td>
   <td style="text-align:left;"> 0.3.2.9000 </td>
   <td style="text-align:left;"> R (&gt;= 3.0.1),
xml2 </td>
   <td style="text-align:left;"> httr (&gt;= 0.5),
selectr,
magrittr </td>
   <td style="text-align:left;"> /Users/calexander/Library/R/3.3/library </td>
   <td style="text-align:left;"> 3.3.1 </td>
  </tr>
</tbody>
</table>

**Comment by curtisalexander** [comment]
Grrr...please close...apologies.

I just realized that `read_html` comes from `xml2`.

This works.

```
lego_movie <- xml2::read_html("http://www.imdb.com/title/tt1490017/")
```

**Comment by stephlocke** [comment]
Sorry for the revive - but the docs for `html()` should be clearer as to where `read_html()` is from. It reads like it should be from rvest

>Description
>html is deprecated: please use read_html() instead.
