### ISSUE TITLE
Failed with error:  ‘there is no package called ‘XML’’

### ISSUE THREAD

**Issue by ilarischeinin** [hadley/rvest#173]
Although it works fine, for some reason this code prints:

```
Failed with error:  ‘there is no package called ‘XML’’
Failed with error:  ‘there is no package called ‘XML’’
```

``` r
library(magrittr)
stations <- "http://en.ilmatieteenlaitos.fi/observation-stations" %>%
  xml2::read_html() %>%
  rvest::html_table()
```

Like I said, the results in `stations` are fine. Also, this happens only on the first run. Subsequent repetitions of the exact same command do not print the error message. This is with the current GitHub version of `rvest`, hash 9a51a5d3be1b8247250da4c3732ebfcf70fd2249.

```
R version 3.3.1 (2016-06-21)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X 10.10.5 (Yosemite)

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] magrittr_1.5

loaded via a namespace (and not attached):
 [1] httr_1.2.1       selectr_0.3-0    R6_2.2.0         tools_3.3.1      parallel_3.3.1   curl_2.1         listenv_0.6.0    Rcpp_0.12.7      xml2_1.0.0       stringi_1.1.2    codetools_0.2-14 stringr_1.1.0   
[13] digest_0.6.10    globals_0.7.0    rvest_0.3.2.9000 future_1.0.1    
```

**Comment by kevinushey** [comment]
I was also able to reproduce this (to repro, the `XML` package should not be installed)

**Comment by kevinushey** [comment]
Smaller repro:

```
> rvest:::make_selector("tr")
Failed with error:  'there is no package called 'XML''
Failed with error:  'there is no package called 'XML''
[1] ".//tr"
```

**Comment by kevinushey** [comment]
It looks like this is ultimately emitted by the `selectr` package:

```
> selectr::css_to_xpath("tr", prefix = ".//")
Failed with error:  'there is no package called 'XML''
Failed with error:  'there is no package called 'XML''
[1] ".//tr"
```

We could report this upstream to https://github.com/sjp/selectr.

**Comment by ilarischeinin** [comment]
Thanks for the detective work.

It seems this is actually already fixed on GitHub. The current CRAN version is `0.3-0`, and GitHub says `0.3-1`. The fix is the addition of argument `quietly=TRUE` [here](https://github.com/sjp/selectr/blob/025c926c62607cead4de72b16f08ef372d3e0a92/R/zzz.R#L20). So, with `devtools::install_github("sjp/selectr")` the error message goes away.

I'll close the issue. My apologies that it was in the wrong place to begin with.

**Comment by tomwwagstaff** [comment]
Just experienced this exact same issue with rvest version 0.3.2
