### ISSUE TITLE
read_html causing core dump for some links

### ISSUE THREAD

**Issue by gunawebs** [hadley/rvest#223]
Please see the code below. For some links, this is causing R to do a Core Dump. I have just put in a sample link, that may help in debugging

The OS is Ubuntu 16.04.4 LTS (GNU/Linux 4.4.0-75-generic x86_64)

>R

R version 3.3.3 (2017-03-06) -- "Another Canoe"
Copyright (C) 2017 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> packageVersion("rvest")
[1] ‘0.3.2’
> link <- 'https://www.xerox.com/en-us/digital-printing/custom-print-production'
> library(rvest)
Loading required package: xml2
> result <- read_html(link)
*** %n in writable segment detected ***
Aborted (core dumped)

Note:

1. Same link(s) work fine on mac

2. Many other links work fine on Ubuntu

3. Attaching the R file with a reproducible example. Please let me know if I can provide any other inputs

[rVestIssueOnUbuntu.txt](https://github.com/hadley/rvest/files/2198376/rVestIssueOnUbuntu.txt)

**Comment by ambravan** [comment]
Thanks for reporting this!

**Comment by jimhester** [comment]
I can't reproduce this, what version of the xml2 package and libxml2 do you have?

```r
packageVersion("xml2")
#> [1] "1.2.0"
xml2:::libxml2_version()
#> [1] "2.9.1"
```

**Comment by gunawebs** [comment]
Thanks so much. xml2 was older
> packageVersion("xml2")
[1] ‘1.1.1’
The error vanished once I updated
