### ISSUE TITLE
why no work?

### ISSUE THREAD

**Issue by itellin** [hadley/rvest#54]
senator.site = POST(
    "http://bioguide.congress.gov/biosearch/biosearch1.asp", 
    body = list(
        lastname = "", 
        firstname = "", 
        position = "Senator", 
        state = "", 
        party = "", 
        congress = "111"
    ), 
    multipart = F
)

senators = html(senator.site) %>% html_nodes("table") %>% html_table() %>% .[[2]]
this is ok.
but:
url = "http://bioguide.congress.gov/biosearch/biosearch.asp"
s = html_session(url)
f0 = html_form(s)
f1 = set_values(f0[[1]], position = "Senator", congress = 111)
test = submit_form(s, f1)
Error in vapply(elements, encode, character(1)) : 
  values must be length 1,
 but FUN(X[[18]]) result is length 0

**Comment by hadley** [comment]
This now works for me - I think I just fixed the underlying bug
