### ISSUE TITLE
Recv failure: Connection reset by peer

### ISSUE THREAD

**Issue by funnng** [hadley/rvest#55]
trying to scrape http://www.nytimes.com/
```
html_session('http://www.nytimes.com/', verbose(), user_agent('Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/600.1.25 (KHTML, like Gecko) Version/8.0 Safari/600.1.25'))
```
but got the error
```
Error in function (type, msg, asError = TRUE)  : 
  Recv failure: Connection reset by peer
```
i check http://stackoverflow.com/questions/10285700/curl-error-recv-failure-connection-reset-by-peer-php-curl this issue, but it seems that there is no relation with this.

**Comment by hadley** [comment]
Works for me - this is likely to be a network problem on your end.
