### ISSUE TITLE
Resolving form URLs

### ISSUE THREAD

**Issue by MrFlick** [hadley/rvest#60]
The code for resolving URLs seems to not be working. Specifically the code in [submit_form](https://github.com/hadley/rvest/blob/5f34d623ddef190831da7736d9709d89672fbaae/R/form.R#L266). There's the line

    url <- XML::getRelativeURL(session$url, form$url)

but the signature for `XML::getRelativeURL` is 

    getRelativeURL(u, baseURL, sep = "/", addBase = TRUE, simplify = TRUE)

so the "base" URL should go second which means that the code should be

    url <- XML::getRelativeURL(form$url, session$url)

Compare

    XML::getRelativeURL("http://homepage.com", "form.php")
    # [1] "http://homepage.com"
    XML::getRelativeURL("form.php", "http://homepage.com")
    # [1] "http://homepage.com/form.php"

**Comment by MrFlick** [comment]
A [pull request](https://github.com/hadley/rvest/pull/61) has been created.

**Comment by hadley** [comment]
Should be fixed now
