### ISSUE TITLE
Is there a way to set cookies before connecting to a webpage?

### ISSUE THREAD

**Issue by MarcinKosinski** [hadley/rvest#72]
One can use `cookies(html_session( webpage_url ) )` to check the session cookies
but is there a way to specify exact cookie before connecting to  a session? I'd like to download the
content of a webpage but only when I enter with a cookie that starts with `4`.

Now I am doing it in `while` loop that isn't the best solution:
````{Ruby}
logic <- TRUE
while( logic ){
WP <- html_session("http://www.wp.pl/")
if ( substr( WP$response$cookies$statid, 1, 1) == "4" ){ logic <- FALSE}
}
````

Any idea on how to do this?

**Comment by hadley** [comment]
You'll need to parse the `set-cookie` header yourself. Start with:

```R
WP <- html_session("http://www.wp.pl/")
headers <- httr::headers(WP)

cookies <- unlist(headers[names(headers) == "set-cookie"])
crumbs <- stringr::str_split_fixed(cookies, "; ", 4)
stringr::str_split_fixed(crumbs[, 1], "=", 2)
```

**Comment by MarcinKosinski** [comment]
Thanks for response. 
I didn't know about `header` function from `httr` package. 
I also didnt' know that the name of specific cookie I'd like to set is confusingly `set`.
You showed the way of extracting cookies that their header is named `set-cookie` but I still do not see the moment where I can set `statid` cookie when starting session with `html_session`.

In my opinion this will change cookies only in my global environment, not in the `html_session`. The reason I am asking about that is a fact that this webpage has different layout for different users depending on their `statid` cookie and I'd like to use `rvest` to automatically test if every layout works fine.

````{Ruby}
library(rvest)
WP <- html_session("http://www.wp.pl/")
headers <- httr::headers(WP)

cookies <- unlist(headers[names(headers) == "set-cookie"])
crumbs <- stringr::str_split_fixed(cookies, "; ", 4)
set_cookies <- stringr::str_split_fixed(crumbs[, 1], "=", 2)
substr( set_cookies[4:5, 2], start = 1, stop = 1) <- "4"
set_cookies
````

**Comment by hadley** [comment]
It's a bit confusing what you want. Do you want want to see the cookies sent to you by the server? Or do you want to send new cookies to the server?

**Comment by MarcinKosinski** [comment]
I'd like to send new cookies to the server. Do you think it is possible?

**Comment by MarcinKosinski** [comment]
I finally managed to do this using this code:

````{Ruby}
html_session("http://dynamic.h157.dhcp.dev:9108/?time=13", set_cookies(`_wpaw` = "A01B30C04C06C09D02E01F08G01H04ZA0ZB0ZC0ZD1ZF1ZG0",
																											 statid = "e46d59edaea8194bf0e87ecbde34c405:f4b461:1427113628:v3"),
		 	 add_headers(`_wpaw` = "A01B30C04C06C09D02E01F08G01H04ZA0ZB0ZC0ZD1ZF1ZG0",
		 	 						statid = "e46d59edaea8194bf0e87ecbde34c405:f4b461:1427113628:v3"))
````
