### ISSUE TITLE
submit_form generates 'Error: length(url) == 1 is not TRUE'

### ISSUE THREAD

**Issue by hsancen** [hadley/rvest#73]
Pretty new here so sorry in advance if this is user error! 

I'm trying to scrap web data but first step requires a login. I've successfully been able to log into other websites but I get a weird error with this website.

    library("rvest")
    library("magrittr")    

    research <- html_session("https://www.fitchratings.com/")

    signin <- research %>%
      html_nodes("form") %>%
      extract2(1) %>%
      html_form() %>%
      set_values (
        'userName' = "abc",
        'password' = "1234"
         )
    
    research <- research %>%
      submit_form(signin)

When I run the 'submit_form' line I get the following error:

    > research <- research %>%
    + submit_form(signin)
    Submitting with '<unnamed>'
    Error: length(url) == 1 is not TRUE

Submitting with unnamed is correct b/c there is no name assigned to the sign in button. Thanks!

**Comment by hadley** [comment]
Should be fixed now. Dumb mistake on my part :/

**Comment by gideonmagnus** [comment]
I'm having the same issue. Here is my code:

```
if (!require(rvest)) {install.packages("rvest")}; require(rvest)
if (!require(dplyr)) {install.packages("dplyr")}; require(dplyr)

url <- "https://www.vrbo.com/4200761ha"
session.temp <- html_session(url)
form.unfilled <- session.temp %>% html_node("form") %>% html_form()
form.filled <- form.unfilled %>%
  set_values('checkin' = "2020-08-01",
             'checkout' = "2020-08-10")
session <- submit_form(session.temp, form.unfilled)

```

I am using the github version of rvest.

Thanks

**Comment by Waldi73** [comment]
Same problem with : 
```
library(rvest)
url<-"https://stackoverflow.com/questions"
(session<-html_session("https://stackoverflow.com/questions"))
(form<-html_form(session)[[2]])
(filled_form<-set_values(form, tagQuery = "ggplot"))

#Avoid error message
filled_form$url <- ""

searched<-submit_form(session, filled_form)
```
The work-around to avoid the error message isn't documented : is it an expected behaviour?

**Comment by hadley** [comment]
@gideonmagnus please file an new issue with a reprex made by the [reprex package](http://reprex.tidyverse.org)? That makes it easier to see both the input and the output, formatted in such a way that I can easily re-run in a local session.
