### ISSUE TITLE
rvest doesn't appear to work in deployed Shiny environment

### ISSUE THREAD

**Issue by salauer** [hadley/rvest#75]
I can use rvest in Shiny locally, but once I deploy it to my shinyapps.io, I get the following error:

Error in do.call(method, list(parsed_selector)) : 
  could not find function "xpath_element"
Calls: runApp ...  -> selector_to_xpath ->  -> do.call
Execution halted

I have my app in a github repo salauer/ncaa_proj2015. It works on my shinyapps.io when I comment out the rvest part of global.R. The only functions I used from rvest were html(), html_nodes(), html_text(), and html_attr("href").

**Comment by hadley** [comment]
It's probably a namespace issue with the XML package. Since rvest no longer uses XML (and instead uses xml2), this problem should have hopefully gone away now.

**Comment by eddelbuettel** [comment]
I hit me today on Travis with all current packages:  

```r
    call: do.call(method, list(parsed_selector))
    error: could not find function "xpath_element"
```

**Comment by hadley** [comment]
@eddelbuettel would you mind creating a reprex? Or at least including the result of `traceback()`? 

I grepped both rvest and xml2 and neither uses xpath_element or do.call.

**Comment by eddelbuettel** [comment]
Sure.  Look at all the failed Travis runs from the branch I worked on yesterday for the [gtrendsR](https://github.com/PMassicotte/gtrendsR) package, ie look here and see builds #289 to #292 of the 'feature/travis_with_test' branch.

Upshot:  The code works on a current distro (ie Ubuntu 16.10).  I fails mercilessly with Ubuntu 14.04.  Sadly that is all we get from Travis, so rvest and friends appear to be unuseable there.

As luck will have it, @PMassicotte is rewriting how access the Google API and soon we may no longer need rvest.

**Comment by eddelbuettel** [comment]
Oh, and I should add, I then tried to get to it via Ubuntu 14.04 in Docker at home, and got the same.

Somehow something old and different gets in the stack.

**Comment by MarkEdmondson1234** [comment]
I got this too on Debian Jessie, but in case anyone else runs across it it was solved by reinstalling `xml2`
