### ISSUE TITLE
html_form

### ISSUE THREAD

**Issue by englianhu** [hadley/rvest#76]
```{r}
> library(rvest)
> library(pipeR)
> lnk <- 'http://www.sbobetonline.com/euro/football'
> lnk %>>% html_session %>% .$response %>% .$headers #wondered if need to setup header
$`cache-control`
[1] "no-cache, no-store"

$pragma
[1] "no-cache"

$`content-type`
[1] "text/html; charset=utf-8"

$`content-encoding`
[1] "gzip"

$expires
[1] "-1"

$`last-modified`
[1] "3/29/2015 11:24:01 AM GMT"

$vary
[1] "Accept-Encoding"

$`set-cookie`
[1] "ASP.NET_SessionId=3m1pp3to01cebatxf1tv5vfy; path=/; HttpOnly"

$`set-cookie`
[1] "lang=en; domain=.sbobetonline.com; expires=Wed, 01-Apr-2015 15:24:01 GMT; path=/; secure; HttpOnly"

$`set-cookie`
[1] "visited=yes; domain=.sbobetonline.com; expires=Mon, 30-Mar-2015 15:24:01 GMT; path=/; secure; HttpOnly"

$`set-cookie`
[1] "last_visit=euro; domain=.sbobetonline.com; expires=Tue, 29-Sep-2015 15:24:01 GMT; path=/; secure; HttpOnly"

$date
[1] "Sun, 29 Mar 2015 15:24:00 GMT"

$`content-length`
[1] "25492"

$`set-cookie`
[1] "odnbv9=218235146.20480.0000; path=/"

attr(,"class")
[1] "insensitive" "list"       
> lnk %>>% html_session %>% .$response %>% .$cookies # wondered if need to setup cookies
$ASP.NET_SessionId
[1] "ibrdsv5twj1fj5vjmdhqnlbb"

$lang
[1] "en"

$visited
[1] "yes"

$last_visit
[1] "euro"

$odnbv9
[1] "84017418.20480.0000"

> web <- lnk %>>% html_session
> user <- lnk %>>% html_session %>>% html_node(xpath='//*[@id="username"]') %>>% set_values(., 'username'="xxxxxxx") #用户名 xxxxxxx
Error in form$fields : object of type 'externalptr' is not subsettable
> pass <- lnk %>>% html_session %>>% html_node(xpath='//*[@id="username"]') %>>% set_values(., 'password'="xxxxxxx") #密码 xxxxxxx
Error in form$fields : object of type 'externalptr' is not subsettable
> submit_form(web, user, pass)
Error in lapply(x, f) : object 'user' not found

Did you mean:  nstr  ?
submit_form(web, nstr, pass)
> 
> #'@ domain=.sbobetonline.com
> #'@ ASP.NET_SessionId=jx0jswds3w3jsoo0awxc4kyd
> #'@ lnk2 %>>% getURL(., cookies='jx0jswds3w3jsoo0awxc4kyd; domain=.sbobetonline.com')
> #'@ getURL(lnk2, cookie='jx0jswds3w3jsoo0awxc4kyd; domain=.sbobetonline.com')
```
May I know how to set_values and submit_form for this case?

**Comment by hadley** [comment]
That url doesn't resolve for me, but I'd expect your code to look more like this:

```R
library(rvest)
sess <- html_session('http://www.sbobetonline.com/euro/football')

form <- sess %>% 
  html_node(xpath='//*[@id="username"]') %>%
  html_form() %>% 
  set_values(., 'username'="xxxxxxx") 

sess %>% submit_form(form)
```

**Comment by englianhu** [comment]
Hi,

> library(rvest)
> sess <- html_session('http://www.longmirror.com/euro/football')
>
> form <- sess %>%
+     html_node(xpath='//*[@id="username"]') %>%
+     html_form() %>%
+     set_values(., 'username'="xxxxxxx")
Error: XML::xmlName(x) == "form" is not TRUE
>
> sess %>% submit_form(form)
Error in lapply(x, f) : object 'form' not found

Sounds unable scrape the xml_form. Any solution.
Thank you.

Best Regards,
Ryo, Eng


On Thu, Apr 16, 2015 at 3:12 AM, Hadley Wickham <notifications@github.com>
wrote:

> Closed #76 <https://github.com/hadley/rvest/issues/76>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hadley/rvest/issues/76#event-282435642>.
>



-- 
®

**Comment by englianhu** [comment]
Hi,

> sess <- html_session('http://myr.ibet.uk.com/General/NoneLogin/MainPage/')
> sess %>>% html_form
[[1]]
<form> '<unnamed>' (GET server-side-script.php)
  <select> 'country-options' [1/2]
  <input submit> '': Select

[[2]]
<form> 'loginform' (POST /General/NoneLogin/Login)
  <input text> 'UserName':
  <input password> 'Password':
  <input text> 'CaptchaValue':
  <input hidden> 'MvcCaptchaHiddenInputId':
Q1RvekRoc3NJd0J3WXp4YkRFY2pJUUlzSnhRVVZsZ0xKMlZiU1NsZkZDVjVPUlZBQ3dsZ1Buc3dCUXdiTVY5WkxnRVpJUjRhQ0JJakVEcytLa2NPTzJRT0VnaG1CV2hWT3dCU0NoWkNmeW9USHdaZU4zQnlSUT09

> CapVal <- sess %>>% html_form %>% .[[2]] %>% .$fields %>%
.$MvcCaptchaHiddenInputId %>% .$value
> form <- sess %>>% html_form %>% .[[2]] %>>%
set_values('UserName'='xxxxxxx', 'Password'='xxxxxxx',
'CaptchaValue'=CapVal)
> iBET <- sess %>>% submit_form(form)
Error in names(submits)[[1]] : subscript out of bounds
> rm(CapVal)

Unable to login the website, may I know how to cope with the issue of the
Captcha Value? After that, this link
http://ibet2.ascbet.com/IBET/Main.aspx (this
iSport webpage only accessible after login) is a XML doc which I need to
setup API, scrape data and start the remote trading.

Thanks appreciated.

Best,
Ryo


On Sun, Apr 19, 2015 at 6:30 PM, Ryo Eng <englianhu@gmail.com> wrote:

> Hi,
>
> > library(rvest)
> > sess <- html_session('http://www.longmirror.com/euro/football')
> >
> > form <- sess %>%
> +     html_node(xpath='//*[@id="username"]') %>%
> +     html_form() %>%
> +     set_values(., 'username'="xxxxxxx")
> Error: XML::xmlName(x) == "form" is not TRUE
> >
> > sess %>% submit_form(form)
> Error in lapply(x, f) : object 'form' not found
>
> Sounds unable scrape the xml_form. Any solution.
> Thank you.
>
> Best Regards,
> Ryo, Eng
>
>
> On Thu, Apr 16, 2015 at 3:12 AM, Hadley Wickham <notifications@github.com>
> wrote:
>
>> Closed #76 <https://github.com/hadley/rvest/issues/76>.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/hadley/rvest/issues/76#event-282435642>.
>>
>
>
>
> --
> ®
>



-- 
®

**Comment by englianhu** [comment]
Ryo  Eng® would like to share papers and updates with you.

Accept Ryo  Eng®'s invitation:
http://academia.edu/t/a-Kf5XyUt-batE4f/Yes-reply%2B006e48be673563b970243da3ab1c3b12f39ae37316cf9b7192cf0000000111467a3792a169ce03e0e470-at-reply.github.com-is-an-academic-or-graduate-student

Ryo  Eng® has invited you to Academia.edu, a global network of over 23,662,800 researchers. After you sign up, you'll be able to share your papers, see analytics on your profile and papers, follow other people in your field, and more.

Thanks,
The Academia.edu Team

For more information visit https://www.academia.edu/t/a-Kf5XyUt-batE4f/press or contact us: feedback@academia.edu

-----
You can opt out of receiving these kinds of emails from Academia.edu with the link below:
https://www.academia.edu/t/a-Kf5XyUt-batE4f/optout/7c4ca7a3159f4b9b3810c40642c932bf

Academia.edu, 251 Kearny St., Suite 520, San Francisco, CA, 94108

**Comment by englianhu** [comment]
hadley/rvestさん

LinkedInでつながってください。よろしくお願いします。

®γσ

®γσさんのリクエストを承認する: https://www.linkedin.com/e/v2?e=0-ik8409cb-c1&t=ssuw&tracking=eml-guest-invite-cta&ek=invite_guest&sharedKey=MY1MsJcb&invitationId=6100955036941119489








本メールはLinkedInのつながりリクエストをご案内するものです。LinkedInは、あなたのメールアドレスを知り合いの紹介機能に使用します。メール購読を停止するには次のリンクをクリックしてください: https://www.linkedin.com/e/v2?e=0-ik8409cb-c1&t=lun&midToken=AQFmrFVhGEd36Q&ek=invite_guest&loid=AQHtQoVJ1R-VmAAAAVKryZ53T2ae1lbdHEupy5X4FXDnzFd0Dt9v6-Fbqf0GoNsQy09PApEmuQXX6KkDMWVWqHtrhdQz5Zcknl_sOJP3QfCGqFlPMnaBw3uS06HTOM3Oem3lfdftW3CgHtV3JcqNh9ph5nRLPktQBc06VZ-03i09CQspnN780hJez8Ni58EO7_E1&eid=0-ik8409cb-c1


本メールはreply@reply.github.comに送信されています。

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=0-ik8409cb-c1&a=customerServiceUrl&ek=invite_guest

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043.LinkedInおよびLinkedInのロゴは、LinkedInの登録商標です。

**Comment by hadley** [comment]
@englianhu you are generating a lot of github spam

**Comment by englianhu** [comment]
®γσ Eng would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/e/v2?e=km95n4-ikge3rmt-94&a=preRegInvite&ek=first_guest_reminder_01&li=14&m=hero&ts=accept_text&sharedKey=MY1MsJcb&invitationID=6100955036941119489

View ®γσ Eng&#39;s profile: https://www.linkedin.com/e/v2?e=km95n4-ikge3rmt-94&a=preRegInvite&ek=first_guest_reminder_01&li=3&m=hero&ts=profile_text&sharedKey=MY1MsJcb&invitationID=6100955036941119489





本メールはLinkedInのつながりリクエストをご案内するものです。LinkedInは、あなたのメールアドレスを知り合いの紹介機能に使用します。購読停止: https://www.linkedin.com/e/v2?e=km95n4-ikge3rmt-94&t=lun&midToken=AQFmrFVhGEd36Q&ek=first_guest_reminder_01&li=16&m=unsub&ts=HTML&eid=km95n4-ikge3rmt-94&loid=AQEQOnoXtlIgpwAAAVLKb7MDlAaYTdEV_c2cr476jedbj7Tw165ZGUNtekcSL0ewgt8JmUrXojShbvTVu-0GCnyJA3I0JWuaV2dLj49J8a_8zV36cv73ft6XCin-2We9h1INcBWGUFL3qBQAQxhJU17yxMtlTxAKhHAKpWFku2At_0rF5J4ifj1j9Z4Vhumj_KuD

本メールはreply@reply.github.comに送信されています。

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=km95n4-ikge3rmt-94&a=customerServiceUrl&ek=first_guest_reminder_01

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043.LinkedInおよびLinkedInのロゴは、LinkedInの登録商標です。
