### ISSUE TITLE
Validating if a string is valid html

### ISSUE THREAD

**Issue by jpmarindiaz** [hadley/rvest#81]
I am trying to scrape some html text. 
It happens that some times the text doesn't have any html tags so I get an error when trying to read the html because `read_html` thinks I am reading a file.

```
read_html("blabla")
Error: 'blabla' does not exist in current working directory ('/Users/jpmarindiaz/Dropbox (personal)/randommonkey/datasketch/users/lsv/apps/historico').
```
I am using `grepl("<([[:alpha:]][[:alnum:]]*)(.[^>]*)>([.^<]*)",x) ` to validate my stings before passing them to `read_html`. 

I am just wondering... does it make sense to include some sort of html validation in the package itself?
Or does it exist already?

**Comment by hadley** [comment]
If `read_html()` succeeds, in some sense it's valid html.
