### ISSUE TITLE
importFrom(xml2,read_html)

### ISSUE THREAD

**Issue by nicolasCoutin** [hadley/rvest#83]
According to `README.md` I think `NAMESPACE` needs to `importFrom(xml2, read_html)`

![screen shot 2015-05-08 at 11 05 10 pm](https://cloud.githubusercontent.com/assets/6063192/7548953/c91f8980-f5d6-11e4-8ae2-47630292da27.png)

**Comment by hadley** [comment]
`read_html` is defined in rvest?
