### ISSUE TITLE
wait html_table() is not a constructor function?

### ISSUE THREAD

**Issue by nicolasCoutin** [hadley/rvest#84]
### Synopsis

why does `html_table()` go against the grain (or at least what I expected)?

```r
data.frame() # dplyr::data_frame()
matrix()
list()
```

### wordy

I expected a function named `html_table()` to:

1.  __construct__ a `<table></table>` from its input as do `data.frame()`, `list()`, `matrix()`, `structure()`, ...  or at least in this world of  `knitr::kable()`, `ascii::ascii()`, `pander::pandoc.table()`, ... to

2. __convert__ an object into a `<table></table>`. 

I've come to take for granted the general distinctions between constructor functions, converting/coercing functions and predicate functions.

###  `c("my" , rep("$0.01", 2))`

IMHO to keep this awesomeness `html_table()` should be re-born `parse_html_table()` or equivalently informative.

**Comment by hadley** [comment]
Because rvest is all about parsing - otherwise practically every function in rvest would need to be prefixed by `parse_`
