### ISSUE TITLE
extract text form node without re-encoding?

### ISSUE THREAD

**Issue by npjc** [hadley/rvest#86]
##### Would it be possible to expose a parameter in `html_text()` where I can keep the html encoding?

As an example:
```r
read_html("<code>x &lt;- 1</code>") %>% html_node("code") %>% html_text()
#> [1] "x <- 1"
```

I.e. I want this result:

`#> [1] "x &lt;- 1"`

I think it would have to go all the way back to [xml2 here](https://github.com/hadley/xml2/blob/8de3f6ac79e39720301364d07e11c058291dd871/src/xml2_node.cpp#L29-37).

(or if there is already a straightforward way to do this I haven't figured it out. I currently use `htmltools::htmlEscape()`) thanks ahead of time !

**Comment by hadley** [comment]
I don't think there's any way to "keep" the original encoding as it's lost during parsing. Why do you want it?

**Comment by nicolasCoutin** [comment]
Ok.

I'm extract texting from html node text then modify and replace but inject in special delimiters themselves into code blocks whch `knitr::knit_expand()` then processes.
