### ISSUE TITLE
toString.XMLNode / innerHTML functionality

### ISSUE THREAD

**Issue by javrucebo** [hadley/rvest#87]
In rvest 0.2 I was able to extract the html/xml-code of a node with `toString.XMLNode` from XML package. This is no longer out of the box possible with the switch to xml2 in rvest 0.2.0.900.

The `write_xml` function in current version has also the desired functionality but only allows to write to an external file and not to a variable.

Can you add such functionality?

**Comment by hadley** [comment]
You can use `as.character()`
