### ISSUE TITLE
Potential bug in html_node when tags dont contain text

### ISSUE THREAD

**Issue by ramnathv** [hadley/rvest#88]
Consider the following example

```r
x = "<div id='x'></div>"
html_node(html(x), 'div')
```

It returns a div with a self-closing tag, which is not valid in HTML5

```r
<div id="x"/> 
```

Adding a space resolves this issue (`x = "<div id='x'> </div>"`), but I was wondering if this was intended behavior or a bug.

**Comment by hadley** [comment]
What do you mean returns? It returns a pointer to the node in the xml tree, which is then rendered using a print method.
