### ISSUE TITLE
Error in stri_locate_first_regex(string, pattern, opts_regex = attr(pattern,  :    Syntax error in regexp pattern. (U_REGEX_RULE_SYNTAX)

### ISSUE THREAD

**Issue by dbuijs** [hadley/rvest#94]
Hi,

Flagging this as a new issue because it was previously closed:

https://github.com/hadley/rvest/issues/32

Just got this error (exactly as described in the original issue) for the first time today. I never saw it before (including up to and after Dec 31, 2014). Uninstalling and reinstalling stringr from CRAN did not resolve the issue. Here's the code that triggered the error:

extractdate <- html_session(url) %>%
  html_nodes("td:contains('allfiles.zip')+ td")

Edit: Still have the error after uninstalling/reinstalling rvest from GitHub

**Comment by dbuijs** [comment]
Resolved by updating R to 3.2.0. I don't know if this was the actual problem, but a fresh rocker/ropensci image set everything right.

**Comment by cawthm** [comment]
Thank you for your response.  I'm not really sure how to do what you said, and googling it didn't much help either.  Can you point me in a direction?

**Comment by dbuijs** [comment]
I run RStudio server from a Docker image called rocker/ropensci: https://registry.hub.docker.com/u/rocker/ropensci/

This is a way of running R and RStudio in a Linux container that contains all relevant dependencies and configuration details, and that you can simply update to the most recent versions of everything. When I say I rebuilt the image, I ran a script that updated all the included packages (both linux and R). 

I'm guessing that the error is somewhere in the dependency chain for either rvest or stringr, but I haven't really been looking too hard since just updating everything fixed the problem.
