### ISSUE TITLE
P elements nested inside a H1 element are not extracted as expected

### ISSUE THREAD

**Issue by jullybobble** [hadley/rvest#99]
In the following code, I would expect `headers[[2]]` to contain the `p` element with the "Title 1b" text; but instead, after parsing, `headers[[2]]` is empty and `p` is a sibling of the `h1` elements:

``` r
library(rvest)
doc <- html('<!DOCTYPE html>
<html>
  <body>
    <h1>Title 1a</h1>
    <h1><p>Title 1b</p></h1>
  </body>
</html>')

headers <- html_nodes(doc, 'h1')

cat(html_text(headers[[1]]) == "Title 1a")
```

    ## TRUE

``` r
cat(html_text(headers[[2]]) == "Title 1b")
```

    ## FALSE

``` r
print(doc)
```

    ## <!DOCTYPE html>
    ## <html><body>
    ##     <h1>Title 1a</h1>
    ##     <h1></h1>
    ## <p>Title 1b</p>
    ##   </body></html>
    ##

This behaviour comes from the `XML` package. A `p` element is not a valid child of a `h1` element in HTML5 (see [h1](http://www.w3.org/TR/html-markup/h1.html#h1) and [phrasing elements](http://www.w3.org/TR/html-markup/common-models.html#common.elem.phrasing) on the W3C site). `XML` apparently silently corrects this by appending the illegal `p` element as a sibling of the `h1` elements.

**The problem:** this changes the semantic of the original HTML page: a text (here "Title 1b") which should inherit from both `h1` and `p`, inherits only from `p` after parsing. Accessorily, this also makes more difficult to scrape pages using this invalid constructs.

For an example where this illegal construct is used, see the [jq Manual](http://stedolan.github.io/jq/manual) where many `h3` have `p` children.

**Comment by hadley** [comment]
Unfortunately this is outside the scope of rvest - I don't have any way to implement a better html tidier
